services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=mongodb
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopasswd
    ports:
      - '27017:27017'
    volumes:
      - mongodb_volume:/data/db
    networks:
      - mongo_backend_network

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongouser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongopasswd
      - ME_CONFIG_BASICAUTH_USERNAME=adminuser
      - ME_CONFIG_BASICAUTH_PASSWORD=adminpasswd
    ports:
      - '8081:8081'
    volumes:
      - mongo_express_volume:/data/db
    networks:
      - mongo_backend_network
volumes:
  mongodb_volume:
  mongo_express_volume:
networks:
  mongo_backend_network:
    driver: bridge